# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yyGP4vBQi_V25bMexnHhI45GmD1YLgMj
"""

import numpy as np
import scipy.stats as stats
import pylab as plt


h =[47,89,90,19,21,14,8,11,6,9,5,16,7,4,13,20,12,18,23,25,10,29,22,15,24,26,17,28,30,27,39,32,34,35,31,36,37,41,33,64,40,38,55,44,43,46,45,49,48,42,52,56,53,62,50,54,67,58,51,57,73,60,69,63,80,59,66,94,101,103,72,68,65,87,83,61,74,78,77,70,82,76,81,88,71,98,75,85,3,95,92,99,91,100,115,212,229,501,401,108,158,463,365,267,123,293,194,156,122,84,128,96,86,116,79,93,97,331,738,837,1090,996,456,457,823,727,922,531,630,319,404,405,408,409,750,654,460,848,559,236,237,238,606,512,415]

h.sort()
hmean = np.mean(h)
hstd = np.std(h)
pdf = stats.norm.pdf(h, hmean, hstd)
print(h, pdf)
# plt.fill_between(section,f(section))
plt.plot(h, pdf) # including h here is crucial

import seaborn as sns
from scipy.stats import norm

data =[47,89,90,19,21,14,8,11,6,9,5,16,7,4,13,20,12,18,23,25,10,29,22,15,24,26,17,28,30,27,39,32,34,35,31,36,37,41,33,64,40,38,55,44,43,46,45,49,48,42,52,56,53,62,50,54,67,58,51,57,73,60,69,63,80,59,66,94,101,103,72,68,65,87,83,61,74,78,77,70,82,76,81,88,71,98,75,85,3,95,92,99,91,100,115,212,229,501,401,108,158,463,365,267,123,293,194,156,122,84,128,96,86,116,79,93,97,331,738,837,1090,996,456,457,823,727,922,531,630,319,404,405,408,409,750,654,460,848,559,236,237,238,606,512,415]
# ax2 = sns.displot(data, stat='percent')
ax = sns.distplot(data)

l1 = ax.lines[0]
sizeofdata=len(l1.get_xydata())
perc=.5
index=int(sizeofdata*perc)
print(index)
print(l1)
x1 = l1.get_xydata()[:40, 0]
y1 = l1.get_xydata()[:40, 1]

print(l1.get_xydata()[:, 1])
ax.fill_between(x1, y1, color="red", alpha=0.3)
plt.show()